######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 1 10:28:57 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fraction.h
SOURCES += fraction-test.cpp fraction.cpp
CONFIG += console
