######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 10 15:39:54 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qconsole.cpp
