######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 10 15:40:16 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += file.cpp
CONFIG += console
