######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 27 11:58:28 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += boardgame.cpp
CONFIG += console
