######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 20 16:48:54 2013
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qtstringdemo.cpp
CONFIG += console
