######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 26 11:56:26 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qtempconv.cpp
CONFIG += console
