######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 31 17:01:15 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += constmembers.cpp
CONFIG += console
