######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 26 18:30:37 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += exactchange.cpp
CONFIG += console
