######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 20 17:13:21 2013
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qtstreamdemo.cpp
CONFIG += console
