"""empty message

Revision ID: 1bb3a9222dd
Revises: None
Create Date: 2013-10-12 21:39:39.652774

"""

# revision identifiers, used by Alembic.
revision = '1bb3a9222dd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
