#+Startup: showall
* Working with lists!
** Moving around in our outline is simple, ~TAB~ will fold or unfold the selected region
** While ~S-TAB~ will fold or unfold the whole document, unfolding one region then all regions!

** You can easily create a list / headline with the current style with ~M-RET~ off the last line
** And move around a list / headline point with ~M-up/down~!
*** You can promote and demote lists as well with ~M-left/right~!
** You can cycle list types with ~S-left/right~
** Unordered lists can start with ~*~, ~-~ or ~+~ characters
** And ordered lists can start with the format ~#.~
** Descriptions for lists can be added after ~::~

* Let's make a list!
** Lord of the Rings
My Favourite scenes are (in this order)
1. The attack of the Rohirrim
2. Eowyn's fight with the witch king
   + this was already my favourite scene in the book
   + I really like Miranda Otto
3. Peter Jackson being shot by Legolas
   - on DVD only
   He makes a really funny face when it happens.
But in the end, no individual scenes matter but the film as a whole.
Important actors in this film are:
- Elijah Wood :: He plays Frodo
- Sean Austin :: He plays Sam, Fodo's friend. I still remember him very well from his role as Mikey
  Walsh in The Goonies.
