######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 20 16:30:14 2013
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += fac.cpp
CONFIG += console
