######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 29 09:36:14 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += constptr.cpp
CONFIG += console
