######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 28 12:21:46 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += newdelete1.cpp
CONFIG += console
