######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 22 01:02:12 2013
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += fac1.cpp
CONFIG += console
