######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 26 13:29:50 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += dicegame.cpp
CONFIG += console
