######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 28 12:01:00 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += pointerdemo.cpp
CONFIG += console
