######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 31 21:36:16 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += thing.h
SOURCES += thing-demo.cpp thing.cpp
CONFIG += console
