######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 10 15:06:55 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += simple.cpp
CONFIG += console
