######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 31 16:26:22 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fraction.h
SOURCES += copyassign.cpp faction.cpp
CONFIG += console
