######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 22 18:28:10 2013
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += clargs.cpp
CONFIG += console
