######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 22 01:35:44 2013
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qsize.cpp
CONFIG += console
