######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 26 10:25:26 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += arithmetic.cpp
CONFIG += console
