######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 22 00:44:46 2013
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qdemo.cpp
CONFIG += console
