######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 22 01:23:42 2013
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qliterals.cpp
CONFIG += console
