######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 31 11:51:47 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fraction.h
SOURCES += fraction-client.cpp fraction.cpp
CONFIG += console
